{% set name = "ragas" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ragas-{{ version }}.tar.gz
  sha256: 9a9536f33ffbcdf28aeb4a4bf648bbf0f1c1be58e357c2442604babf726fe871

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - numpy
    - datasets
    - tiktoken
    - langchain
    - langchain-core
    - langchain-community
    - langchain-openai
    - openai >1
    - pysbd >=0.3.4
    - nest-asyncio
    - appdirs

test:
  imports:
    - ragas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/explodinggradients/ragas/
  summary: Evaluation framework for your Retrieval Augmented Generation (RAG) pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
