{% set name = "ragas" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ragas-{{ version }}.tar.gz
  sha256: a800a5326f0d5bfa086cf8832d4b1031e4b21ff063f83d7d9388ee36e1a93fe6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - gitpython
    - instructor
    - pillow >=10.4.0
    - rich
    - tqdm
    - typer
    - diskcache >=5.6.3
    - pydantic >=2.0.0
    - python >={{ python_min }}
    - numpy
    - datasets
    - tiktoken
    - langchain
    - langchain-core
    - langchain-community
    - langchain-openai
    - openai >=1.0.0
    - pysbd >=0.3.4
    - nest-asyncio
    - appdirs
    - nltk
    - llama-index

test:
  imports:
    - ragas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/explodinggradients/ragas/
  summary: Evaluation framework for your Retrieval Augmented Generation (RAG) pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
