{% set name = "ragas" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ragas-{{ version }}.tar.gz
  sha256: 39d7e7b7a198887a5541b9146dc1a1f70d8f5edf60c5108ce6fa5ddd5b2cbd3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - networkx
    - scikit-network
    - gitpython
    - instructor
    - pillow >=10.4.0
    - rich
    - tqdm
    - typer
    - diskcache >=5.6.3
    - pydantic >=2.0.0
    - python >={{ python_min }}
    - numpy
    - datasets >=4.0.0
    - tiktoken
    - langchain
    - langchain-core
    - langchain-community
    - langchain-openai
    - openai >=1.0.0
    - pysbd >=0.3.4
    - nest-asyncio
    - appdirs
    - nltk
    - llama-index
    - git

test:
  imports:
    - ragas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/explodinggradients/ragas/
  summary: Evaluation framework for your Retrieval Augmented Generation (RAG) pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
