{% set name = "ragas" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ragas-{{ version }}.tar.gz
  sha256: 5b470907ee2590234853dcd56c081afbc0348876a664747b9c3357d8f152b0c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - diskcache >=5.6.3
    - pydantic >=2
    - python >=3.8
    - numpy
    - datasets
    - tiktoken
    - langchain
    - langchain-core
    - langchain-community
    - langchain-openai
    - openai >1
    - pysbd >=0.3.4
    - nest-asyncio
    - appdirs
    - nltk
    - llama-index

test:
  imports:
    - ragas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/explodinggradients/ragas/
  summary: Evaluation framework for your Retrieval Augmented Generation (RAG) pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
